OAP/OAP/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from users import views

urlpatterns = [
    path('', views.home),
    path('home/', views.home),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'))),
]

OAP/users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'users'

urlpatterns = [
    # path('', views.home),
    # path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('userLogin/', views.userLogin, name='userLogin'),
    path('userLogout/', views.userLogout, name='userLogout'),
    path('home/', views.home, name='home'),
    path('info/', views.info, name='info'),
    path('doginfo/', views.doginfo, name='doginfo'),
    path('editdoginfo/<int:dogid>/', views.editdoginfo, name='editdoginfo'),
    path('petslist/', views.petslist, name='petslist'),
    # path('schedule/', views.schedule, name ='schedule'),
    path('mybook/', views.mybook, name='mybook'),
    path('mybooklist/', views.mybooklist, name='mybooklist'),
    path('booking/', views.booking, name='booking'),
    path('cancel/', views.cancel, name='cancel'),
    path('cancelconfirm/<int:appid>/', views.cancelconfirm, name='cancelconfirm'),
    path('reschedule/', views.reschedule, name='reschedule'),
    path('rescheduledetail/<int:appid>/', views.rescheduledetail, name='rescheduledetail'),
    path('availbleschedule', views.availbleschedule, name='availbleschedule'),
    path('availbleschedule/bookDetail', views.bookDetail, name='bookDetail'),
    path('availbleschedule/event-available', views.bookavailable, name='bookavailable'),
    path('availbleschedule/event-booked', views.bookbooked, name='bookbooked'),
    # path('bookSuccess', views.bookSuccess, name ='bookSuccess'),

    # path('users/', include('users.urls')),
    # path('users/', include('django.contrib.auth.urls')),
]

OAP/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


class User(AbstractUser):
    username = models.EmailField(max_length=50, unique=True)

    class Meta(AbstractUser.Meta):
        pass


class userInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=80, default='', blank=True, null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    mobile = models.CharField(validators=[phone_regex], max_length=17)  # validators should be a list
    workPhone = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    home = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list


class Dog(models.Model):
    name = models.CharField(max_length=50)
    breed = models.CharField(max_length=50)
    dob = models.DateField('date of birth')
    owner = models.ForeignKey('User', on_delete=models.CASCADE)


# Create your models here.

# class TimeSchedule(models.Model):
#     weekday = models.DateField()

class Appointments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    msg = models.CharField(max_length=140, default=' ', blank=True, null=True)
    starttime = models.DateTimeField()  # y-m-d-h-m-s
    endtime = models.DateTimeField()
    groomingoptions = models.CharField(max_length=40)
    def getyear(self):
        return self.starttime.year

    def getmonth(self):
        return self.starttime.month

    def getday(self):
        return self.starttime.day

    def getstarthour(self):
        return self.starttime.hour

    def getstartmin(self):
        min = self.starttime.minute
        if int(min) < 10:
            min = '0' + str(min)
        return min

    def getendhour(self):
        return self.endtime.hour

    def getendmin(self):
        min = self.endtime.minute
        if int(min) < 10:
            min = "0" + str(min)
        return min
    # weekday = models.IntegerField() #0-6

OAP/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import User, userInfo, Appointments
from django.core.validators import RegexValidator


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username",)


class LoginForm(AuthenticationForm):
    class Meta(AuthenticationForm):
        fields = ()


class InfoForm(forms.ModelForm):
    # address = forms.CharField(max_length=80)
    # mobile = forms.RegexField(regex=r'^\+?1?\d{9,15}$')
    # error_message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    # workPhone = forms.RegexField(regex=r'^\+?1?\d{9,15}$')
    # error_message="workPhone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    # home = forms.RegexField(regex=r'^\+?1?\d{9,15}$')
    # error_message="Home number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    class Meta:
        model = userInfo
        fields = ['address', 'mobile', 'workPhone', 'home']

'''
class BookForm(forms.ModelForm):
    class Meta:
        model = Appointments
        fields = ['msg']
'''

OAP/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm, InfoForm
from django.contrib.auth import login, authenticate, logout
from django.views.decorators.csrf import csrf_protect
from django.utils import timezone
from .models import userInfo, Dog, Appointments
from .mail import sendEmail, sendSuccessEmail

import time
import re

WEEK = 3
YEAR = 2018
now = timezone.now()


# def sendmail(toemail)
#     print("sending email")
#     send_mail('A reminder for your grooming appointment', 'You have an appointment within 24 hours, please check it.', 'developer@yu.com',
#               ['toemail'], fail_silently=False)
#     print("sent success")

def sendmail():
    now = timezone.now()
    mth = now.month
    hour = now.hour
    minutes = now.min
    second = now.second
    if hour == 11 and minutes == 31 and second == 00:
        print("sending email")
        day = now.day

        day = day + 1
        if day < 29:
            pass
        elif day == 29 and month == 2:
            month = 3
            day = 1
        elif day == 31 and month % 2 == 0:
            if month == 12:
                month = 1
            else:
                month = month + 1
            day = 1
        elif day == 32:
            month = month + 1
            day = 1
        else:
            pass
        next = now

        next.day = day
        appointlist = Appointments.objects.filter(starttime__range=[now, next])
        emaillist = []
        for i in appointlist:
            emaillist.append(i.user)
        for touser in emaillist:
            sendEmail(touser)


# TODO email
def home(request):
    sendmail()
    # sendmail('derakhy@gmail.com')
    return render(request, 'users/home.html')


@csrf_protect
def info(request):
    current_user = request.user
    try:
        userinfo = userInfo.objects.get(user=current_user)
    except:
        userinfo = None
    if request.method == 'POST':
        if userinfo is None:
            userinfo = userInfo()
        userinfo.user = current_user
        userinfo.address = request.POST.get('address')
        userinfo.mobile = request.POST.get('mobile')
        userinfo.workPhone = request.POST.get('workPhone')
        userinfo.home = request.POST.get('home')
        userinfo.save()
        return render(request, 'users/info.html', context={
            'flag': 1,
            'address': userinfo.address,
            'mobile': userinfo.mobile,
            'workPhone': userinfo.workPhone,
            'home': userinfo.home})
    if userinfo is not None:
        return render(request, 'users/info.html', context={'address': userinfo.address,
                                                           'mobile': userinfo.mobile,
                                                           'workPhone': userinfo.workPhone,
                                                           'home': userinfo.home})
    else:
        return render(request, 'users/info.html')


def petslist(request):
    current_user = request.user
    petslist = Dog.objects.filter(owner=current_user)
    context = {'petslist': petslist}
    return render(request, 'users/petslist.html', context)


def editdoginfo(request, dogid):
    current_user = request.user
    dog = Dog.objects.get(owner=current_user, id=dogid)
    print(dog.dob)

    if request.method == 'POST':
        dog.owner = current_user
        name = request.POST.get('name')
        if name is not None and name != '':
            dog.name = name
        print(dog.name)
        breed = request.POST.get('breed')
        if breed is not None and name != '':
            dog.breed = breed
        dob = request.POST.get('dob')
        if dob is not None and dob != '':
            dog.dob = dob
        print(dog.dob)
        dog.save()

        return redirect('../../petslist')

    return render(request, 'users/editdoginfo.html', context={
        'id': dogid,
        'name': dog.name,
        'breed': dog.breed,
        'dob': dog.dob})


def doginfo(request):
    current_user = request.user
    if request.method == 'POST':
        dog = Dog()
        dog.owner = current_user
        dog.name = request.POST.get('name')
        dog.breed = request.POST.get('breed')
        dog.dob = request.POST.get('dob')
        dog.save()
        return redirect('../../users/petslist')
    else:
        return render(request, 'users/doginfo.html')


@csrf_protect
def userLogin(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                print(1)
                return redirect('../../users/home')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', context={'form': form})


def userLogout(request):
    logout(request)
    return redirect('../../users/userLogin')


@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/users/userLogin')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', context={'form': form})


# def schedule(request):
#     return render(request, 'users/schedule.html')


def mybook(request):
    tmp = time.localtime()
    date = time.strftime('%m-%d', tmp)
    datelist = generateDatelist(date, WEEK)
    current_user = request.user
    appointmentsList = Appointments.objects.filter(endtime__gte=now, user=current_user)
    week = [0] * WEEK
    context = {'appointmentsList': appointmentsList, 'week': week, 'datelist': datelist}
    return render(request, 'users/mybook.html', context)


def mybooklist(request):
    current_user = request.user
    appointmentsList = Appointments.objects.filter(endtime__gte=now, user=current_user)
    context = {'appointmentsList': appointmentsList}
    return render(request, 'users/mybooklist.html', context)


class datelist_detail():
    year = 0
    month = 0
    day = 0

    def __init__(self, year, month, day):
        self.year = year
        self.month = month
        self.day = day


def generateDatelist(startDate, WEEK):
    datelist = []
    # datelist.append(startDate)
    month = int(startDate[:2])
    day = int(startDate[3:5]) - 1
    for i in range(0, 5 * WEEK):
        # print(1)
        day = day + 1
        if day < 29:
            pass
        elif day == 29 and month == 2:
            month = 3
            day = 1
        elif day == 31 and month % 2 == 0:
            if month == 12:
                month = 1
            else:
                month = month + 1
            day = 1
        elif day == 32:
            month = month + 1
            day = 1
        else:
            pass
        tmp = datelist_detail(YEAR, month, day)
        # addDate = str(day) + '-' + str(month) + '-' + str(YEAR)
        # print(addDate)
        datelist.append(tmp)
    return datelist


def availbleschedule(request):
    tmp = time.localtime()
    date = time.strftime('%m-%d', tmp)
    # print('start '+ date)
    datelist = generateDatelist(date, WEEK)
    # for i in datelist:
    #     print(i)
    # weekday = time.strftime('%w', tmp)
    appointmentsList = Appointments.objects.filter(endtime__gte=now)
    week = [0] * WEEK
    context = {'appointmentsList': appointmentsList, 'week': week, 'datelist': datelist}
    return render(request, 'users/availbleschedule.html', context)


def format_datetime(datetime):
    year = datetime[6:10]
    month = datetime[0:2]
    day = datetime[3:5]
    pattern_hour = re.compile(r'\s(.+):')
    hour = pattern_hour.search(datetime).group(1)
    pattern_min = re.compile(r':(.+)\s')
    min = pattern_min.search(datetime).group(1)
    ampm = datetime[-2:]
    if ampm == 'PM':
        hour = int(hour) + 12
    if int(hour) < 10:
        hour = '0' + str(hour)
    # if int(min)<10:
    #     min = '0'+str(min)
    value = str(year) + '-' + str(month) + '-' + str(day) + ' ' + str(hour) + ':' + str(min)
    return value


def booking(request):
    current_user = request.user
    dog_list = Dog.objects.filter(owner=current_user)
    if request.method == 'POST':
        # print(2)
        # form = MakeAppointmentsForm(request.POST)
        # print(3)
        # print(request.POST.get('dog', ''))
        # print(form)
        # if form.is_valid():
        appointment = Appointments()
        appointment.user = current_user
        # print(current_user)
        # print(form.cleaned_data.get('starttime'))
        dogname = request.POST.get('dog')
        # print(form.cleaned_data['dog'])
        # print(dogname)
        thedog = Dog.objects.get(name=dogname, owner=current_user)
        appointment.dog = thedog
        appointment.msg = request.POST.get('msg')
        appointment.groomingoptions = request.POST.get('groom')
        appointment.starttime = format_datetime(request.POST.get('starttime'))
        appointment.endtime = format_datetime(request.POST.get('endtime'))

        thedog.save()
        appointment.save()
        msg = 'Book for:' + dogname + ', Option:' + appointment.groomingoptions + ', Start at:' + str(appointment.starttime) + ' To ' + str(appointment.endtime) + ' Message:' + appointment.msg
        sendSuccessEmail(appointment.user.username, msg)
        return render(request, 'users/bookSuccess.html', context={'dogname': dogname,
                                                                  'starttime': appointment.starttime,
                                                                  'endtime': appointment.endtime,
                                                                  'groom': appointment.groomingoptions,
                                                                  'msg': appointment.msg})

OAP/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="icon" href="favicon.ico"/>
    <!--jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

    <!--bootstrap-->
    <link href="{% static 'users/css/bootstrap.min.css' %}" rel="stylesheet"/>
    {#    <script src="{% static 'users/js/bootstrap/bootstrap.min.js' %}"></script>#}
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <!--[if lt IE 9]>
      <script src="js/bootstrap/html5shiv.min.js"></script>
      <script src="js/bootstrap/respond.min.js"></script>
    <![endif]-->
    <!--font-awesome-->
    <link href="{% static 'users/css/font-awesome.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'users/css/pace/dataurl.css' %}" rel="stylesheet"/>
    <script src="{% static 'users/js/pace/pace.min.js' %}"></script>
    <!--jquery.hammer-->
    <script src="{% static 'users/js/jquery.hammer/hammer.min.js' %}"></script>
    <script src="{% static 'users/js/jquery.hammer/jquery.hammer.js' %}"></script>
    <script src="{% static 'users/js/jquery.scrolltopcontrol/scrolltopcontrol.js' %}" type="text/javascript"></script>
    <script src="{% static 'users/js/jquery.extend.js' %}" type="text/javascript"></script>
    <link href="{% static 'users/css/default.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'users/js/default.js' %}" type="text/javascript"></script>
    <!--  jQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

    <!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css"/>

    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

    {% block header %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle show pull-left" data-target="sidebar">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                    class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                    class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'users:home' %}">Better Choose Tom</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'users:info' %}">Edit Personal Info</a></li>
                <li><a href="{% url 'users:doginfo' %}">Add Your Pet</a></li>
                <li><a href="{% url 'users:petslist' %}">Edit Pets Info</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-expanded="false"><i class="fa fa-user fa-fw"></i>&nbsp;&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'users:userLogout' %}?next={{ request.path }}"><i
                                class="fa fa-sign-out fa-fw"></i>&nbsp;Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid all">
    <div class="sidebar">
        <ul class="nav">

            <li><a href="{% url 'users:home' %}">Home</a></li>
            {#            <li><a href="{% url 'users:schedule' %}">Available Schedule</a></li>#}
             <li><a href="{% url 'users:availbleschedule' %}"><i class="fa fa-circle-o fa-fw"></i>&nbsp;Available
                        Schedule</a></li>
            <li class="has-sub">
                <a href="javascript:void(0);"><span>My Appointments</span><i
                        class="fa fa-caret-right fa-fw pull-right"></i></a>
                <ul class="sub-menu">
                    <li><a href="{% url 'users:mybook' %}"><i class="fa fa-circle-o fa-fw"></i>&nbsp;My Appointments Timetable</a></li>
                    <li><a href="{% url 'users:mybooklist' %}"><i class="fa fa-circle-o fa-fw"></i>&nbsp;My Appointments Detail</a></li>


                </ul>
            </li>
            <li><a href="{% url 'users:booking' %}"><i class="fa fa-circle-o fa-fw"></i>&nbsp;Make an
                        Appointment</a></li>
                    <li><a href="{% url 'users:cancel' %}"><i class="fa fa-circle-o fa-fw"></i>&nbsp;Cancel Appointment</a>
                    </li>
                    <li><a href="{% url 'users:reschedule' %}"><i class="fa fa-circle-o fa-fw"></i>&nbsp;Reschedule
                        Appointment</a></li>

        </ul>
    </div>

    {% block content %}{% endblock %}
    <!--end-->
</div>
</body>
</html>

OAP/users/templates/users/cancel.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
    {% if appointmentsList %}
        <h2>Select the appointment you would like to cancel.</h2>

        <br>
        <br>
        <br>
        {% for app in appointmentsList %}
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-3">
                    <div class="form-group shadow-textarea">
                        <label class="form-control" name="name" type="text" readonly>
                            {{ app.dog.name }}
                        </label>
                    </div>
                </div>

                <div class="col-md-4">
                    <label class="form-control" name="name" type="text" readonly>
                        {{ app.starttime }}-{{ app.endtime }}
                    </label>
                </div>
                <div class="col-md-3">
                    <a href="{% url 'users:cancelconfirm' app.pk %}">
                    <button type="button" class="btn btn-danger" value="submit">Cancel</button>
                    </a>
                </div>
                <div class="col-md-1"></div>

            </div>
            <br>
            <br>
        {% endfor %}
    {% else %}
        <h2>You have no appointments yet.</h2>
    {% endif %}
{% endblock content %}

OAP/users/templates/users/event-booked.html
<div class="event-info">
    <div>
        This period is already booked by other customers.
    </div>
</div>

OAP/users/templates/users/login.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Login</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>Login</h3>
                <form class="form" action="{% url 'users:userLogin' %}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                </form>
                <div class="flex-left top-gap text-small">
                    <div class="unit-2-3"><span>No username？<a href="{% url 'users:register' %}">Register</a></span></div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

OAP/users/templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Register</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>Register</h3>
                <p>#Username should be your Email</p>
                <form class="form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">Register Confirm</button>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="{% url 'users:userLogin' %}">Already Registered?</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

OAP/users/templates/users/rescheduledetail.html
{% extends 'users/base.html' %}
{% load static %}
{% block header %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <link href="{% static 'users/css/bootstrap-datetimepicker.css' %}" rel="stylesheet">
    <script src="{% static 'users/js/bootstrap-datetimepicker.min.js' %}"></script>

    .shadow-textarea textarea.form-control::placeholder {
    font-weight: 300;
    }
    .shadow-textarea textarea.form-control {
    padding-left: 0.8rem;
    }

{% endblock %}
{% block content %}
    {% if appointment %}
        <form action="{% url 'users:rescheduledetail' appointment.id %}" method="post">
            {% csrf_token %}
            <!--{{ form.date }} -->
            <h2>Reschedule Appointments Form</h2>
            <br>
            <br>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label for="dog">Pets Name:</label>
                    </div>
                    <div class="col-md-5">
                        <label class="form-control" name="name" type="text" readonly>
                            {{ appointment.dog.name }}
                        </label>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>
            <br>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label for="groom">Grooming Options:</label>
                    </div>
                    <div class="col-md-5">
                        <select class="form-control" name="groom">
                            <option>Wash Only</option>
                            <option>Wash and Nail Clipping</option>
                            <option>Deluxe Grooming</option>
                        </select>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>

            <br>
            <div class="control-group">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label class="control-label">StartTime Picking</label>
                    </div>
                    <div class="col-md-5">
                        <div class="input-group date" id="starttime">
                            <input type="text" class="form-control" name="starttime"
                                   placeholder="{{ appointment.starttime }}"/>
                            <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar">
                            </span>
                        </span>
                        </div>
                        <script>$('#starttime').datetimepicker();</script>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>

            <br>
            <br>

            <div class="control-group">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label class="control-label">EndTime Picking</label>
                    </div>
                    <div class="col-md-5">
                        <div class="input-group date" id="endtime">
                            <input type="text" class="form-control" name="endtime"
                                   placeholder="{{ appointment.endtime }}"/>
                            <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar">
                            </span>
                        </span>
                        </div>
                        <script>$('#endtime').datetimepicker();</script>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>
            <br>
            <br>

            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="form-group shadow-textarea">
                        <label for="id_msg">Leave a message for groomer:</label>
                        <textarea class="form-control z-depth-1" id="id_msg" name="msg" rows="3"
                                  placeholder="Write something here...">{{ appointment.msg }}</textarea>
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>

            <br>
            <br>
            <br>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary" value="submit">Reschedule</button>
                    {#        <input type="submit" value="submit"/>#}
                    <div class="col-md-4"></div>
                </div>
            </div>

            <script type="text/javascript">
                $('.form_datetime').datetimepicker({
                    //language:  'fr',
                    weekStart: 1,
                    todayBtn: 1,
                    autoclose: 1,
                    todayHighlight: 1,
                    startView: 2,
                    forceParse: 0,
                    showMeridian: 1
                });
            </script>
        </form>
    {% else %}
        <h1>You haven't added your pets yet, Please add your pets.</h1>
    {% endif %}
{% endblock content %}
<!-- The rest of my form -->